export default {
  serverUrl: "http://localhost:8000/process_frame",
  storeUrl: "http://localhost:8000/store",
  retrieveUrl: "http://localhost:8000/retrieve",
  lockersSummaryUrl: "http://localhost:8000/lockers/summary",
  frameRate: 10,
  isMobile: /Android|iPhone|iPad/.test(navigator.userAgent),
  personColor: "#00FF00",
  faceColor: "#FF0000",
  borderWidth: 2,
  showPersons: true,
  showFaces: true,
  showConfidence: true,
  showFaceNames: true,
  labelMargin: 3,
  labelPadding: 4,
  mobileLabelFontSize: 16,
  desktopLabelFontSize: 14,
};
